atg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delhi.urls')),
]

delhi/urls.py
from django.urls import path, include
from .import views
urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),   
    path('category/', views.category, name='category'),
    path('subcategory/', views.subcategory, name='subcategory'),
    path('job/', views.job, name='job'),
    path('companydetails/', views.companydetails, name='companydetails'),
    path('searchingstate', views.searchingstate, name='searchingstate'),
    path('searchingcat', views.searchingcat, name='searchingcat'),
    path('searchingsub', views.searchingsub, name='searchingsub'),
    path('searchingjob', views.searchingjob, name='searchingjob'),
    
]

delhi/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name  

class SubCategory(models.Model):     
    name = models.CharField(max_length=200) 
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  

    def __str__(self):
        return self.name

class States(models.Model):     
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name        

class CompanyDetails(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=550, null=True, blank=True)
    no_of_emp = models.CharField(max_length=200, null=True, blank=True)
    state = models.ForeignKey(States, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Jobs(models.Model):
    companydetails = models.ForeignKey(CompanyDetails, on_delete=models.CASCADE)
    jobPosition = models.CharField(max_length=200)
    Location = models.CharField(max_length=200)

    def __str__(self):
        return self.Location

delhi/views.py
from .models import *
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.models import User, auth

def home(request):
    state = States.objects.all().values('name').distinct()   
    context = {'state':state}  
    return render(request, 'home.html', context) 

def category(request):
    c =(request.GET.keys())   
    for i in c:
        c=i    
    category= Category.objects.filter(id__icontains=c)
    if c == 'all':
        category =Category.objects.all()
    context = {
        'category':category
    }    
    return render(request, 'category.html', context)  

def subcategory(request):
    sub = request.GET.keys()
    for i in sub:
        sub = i
    subcategory = SubCategory.objects.filter(name__icontains=sub)
    if sub == 'name':
        subcategory = SubCategory.objects.all()
    context = {
        'subcategory':subcategory}
    return render(request, 'subcategory.html', context)

def job(request):
    job = request.GET.keys()
    for i in job:
        job=i  
    job = Jobs.objects.filter(jobPosition__icontains=job)
    if job == 'all':
        job = Jobs.objects.all()
    context = {
        'jobs': job
    }
    return render(request, 'jobs.html', context)

def companydetails(request):
    company = request.GET.keys()
    for i in company:
        company = i
    
    companydetails = CompanyDetails.objects.filter(name__icontains=company)
    context = {
        'companydetails':companydetails
    }
    return render(request, 'companydetails.html', context)    
  
def searchingstate(request):
    query = request.GET['query']
    states = States.objects.filter(name__icontains=query).values('name').distinct()
    print(states)
    try:
        states[0]
    except:
        return render(request, 'error.html')
    context = {
        'states':states
    }
    return render(request, 'searching.html',context)
def searchingcat(request):
    query = request.GET['query']
    category = Category.objects.filter(name__icontains=query)
    
    try:
        category[0]
    except:
        return render(request, 'error.html')
    context = {
        'category':category
    }
    return render(request, 'searching.html',context)
def searchingsub(request):
    query = request.GET['query']
    category = SubCategory.objects.filter(name__icontains=query)
    try:
        category[0]
    except:
        return render(request, 'error.html')
    context = {
        'category':category,
    }
    return render(request, 'searching.html',context)

def searchingjob(request):
    query = request.GET['query']
    jobs = Jobs.objects.filter(jobPosition__icontains=query)
    try:
        jobs[0]
    except:
        return render(request, 'error.html')
    context = {
        'jobs':jobs,
    }
    return render(request, 'searching.html',context)    


   
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        confirm_password = request.POST['password2']
        if password1==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username taken.")
                return redirect('register')
            elif User.objects.filter(email=email).exists():  
                messages.info(request, "Email address taken.") 
                return redirect('register')
            else:    
                user = User.objects.create_user(username=username, password=password1, email=email)
                user.save()
                messages.info(request, "Successfully Registration.")
                return redirect('login')
        else:
            messages.info(request, "Password not matching.")  
            return redirect('register')  

    else:
        return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect("/")
        else:
            messages.info(request, 'Invalid Username or Password, Please Try Again.')    
            return redirect('login')
    else:
        return render(request, 'login.html')
def logout(request):
    auth.logout(request)
    return redirect("/")

delhi/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    
  </head>
  <body>
    
   
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
        </li>
       
        
        {%if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link">Welcome,  <b class="text-light">{{user.username}}</b></a> 
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logout">Logout</a>
        </li>
         
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="register">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">Login</a>
        </li>
        
        {%endif%}
      </ul>
      
            
    </div>
  </div>
</nav>
    
    {%block content%}
    {% endblock  %}
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
  </body>
</html>

delhi/templates/cat.html
{% extends 'base.html' %}
{% block title %}Category{% endblock  %}
{% block content %}
<br>
<div class="container-fluid">
   <div class="row">

      <div class="col-sm-2">
        <div class="accordion" id="accordionExample">
          {%for cat in category%}
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="{{cat.id}}" aria-expanded="true" aria-controls="collapseOne">
                {{cat.name}}
              </button>
            </h2>

            <div id="{{cat.id}}" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              
              <div class="accordion-body">
              
                {%for i in cat.subcategory_set.all%}
                  <button class="btn btn-info btn-sm" type="button">
                   <a href="{%url 'homeview' i.id%}">
                  {{i.name}}
                  </a>
                  </button>  <br><br>
                {%endfor%}
              </div>
              
            </div>

          </div>
          {%endfor%}
        </div>
      </div>

      <div class="col-sm-10">   
        
      </div>

    </div>
 </div>      


{%endblock%}

delhi/templates/category.html
{% extends 'base.html' %}
{% block title %}Category Scraping{% endblock  %}
{% block content %}
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
      <table class="table">  
        <tbody>
          <tr>
            <td><a type="submit" href="/category/?all" style="text-decoration:none; color:brown">All Category Here...</a></td>
          </tr>
            {%for cat in category%}
              <tr>       
                <td>
                  <a href="/subcategory/?{{cat.name}}" style="text-decoration:none" name="c" id="c">
                    {{cat.name}}</a>
                </td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-sm-8">
    <form class="d-flex" action="/searchingcat" method="get">{% csrf_token %}
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search"  id="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>    
</div>

{% endblock  %}

delhi/templates/catsub.html
{% extends 'base.html' %}
{% block title %}Category{% endblock  %}
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="left-sidebar">                
			    <div class="panel-group category-products brands_products">	
                {%if category %}					
                    {%for ct in category%}			
                    {%for job in jobs%}			
					    <div class="panel panel-default">
					        <div class="panel-heading">
					             <h6 class="panel-title">Searched...<a href="/?catid={{job.id}}">{{ct.category}}</a></h6>
					        </div>
				        </div>
                    {%endfor%}
                    {%endfor%}
                {%else%}
                     <h6 class="text-danger">{{search}}</h6>
                     <h6 class="text-secondary">Error category, try to another</h6>
                {%endif%} 						
			    </div>
            </div>
        </div>           
    </div>
</div>
{% endblock  %}

delhi/templates/collections.html
{% extends 'base.html' %}
{% block title %}Atg Scraping{% endblock  %}
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
           <h3>Hello Collections Category</h3>
               <div class="row">
                    {%for cat in category%}
                        <div class="col-md-4">
                            <a href="{%url 'homeview' cat.id%}">
                                <div class="card">
                                    <div class="card-body">
                                        <strong>{{cat.name}}</strong>                                    
                                    </div>
                                </div>
                            </a>    
                        </div>
                    {%endfor%}
               </div>              
        </div>
    </div>
</div>
{% endblock  %}

delhi/templates/companydetails.html
{% extends 'base.html' %}
{% block title %}Company Details Scraping{% endblock  %}
{% block content %}
 
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">         
            <div class="row">    
                {%for comp in companydetails%}
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">            
                                <strong>{{comp.name}}</strong><br><hr>
                                <p>{{comp.description}}</p><br>
                                <strong>{{comp.state}}</strong><br><hr>
                                <strong>{{comp.no_of_emp}}</strong>
                            </div>
                        </div>
                    </div> 
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock  %}

delhi/templates/error.html
{% extends 'base.html' %}
{% block title %}No Result{% endblock  %}
{% block content %}
<h1>No Result</h1>
{% endblock %}

delhi/templates/index.html
{% extends 'base.html' %}
{% block title %}Category{% endblock  %}
{% block content %}
<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm">
                        {%for com in companydetails%}
                            <div class="card border-success mb-3" style="max-width: 18rem;">
                                <div class="card-header bg-transparent border-success">{{com.name}}</div>
                                    <div class="card-body text-success">                                        
                                        <p class="card-text">{{com.description}}</p>
                                    </div>
                                <div class="card-footer bg-transparent border-success">{{com.state}}</div>
                            </div>
                        {%endfor%}   
                    </div> 
                </div>        
        </div>
        {% comment %} <div class="col-sm-10">   
                
        </div> {% endcomment %}
    </div>
</div>
{%endblock%}

delhi/templates/jobs.html
{% extends 'base.html' %}
{% block title %}Jobs Scraping{% endblock  %}
{% block content %}
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <table class="table"> 
        <thead>
          <tr>     
            <th scope="col">Company</th>
            <th scope="col">JobPosition</th>
            <th scope="col">Location</th>
          </tr>
        </thead>
        <tbody>
          {% for job in jobs  %}
            <tr>    
              <td><a href="/companydetails/?{{job.companydetails.name}}" style="text-decoration: none;">{{job.companydetails.name}}</a></td>
              <td>{{job.jobPosition}}</td>
              <td>{{job.Location}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>  
     <div class="col-sm-4"> 
     <br>
      <form class="d-flex" action="/searchingjob" method="get">{% csrf_token %}
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search"  id="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
     </div> 
  </div>
</div>

{% endblock  %}

delhi/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock  %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 "></div>
      <div class="col-sm-6 bg-light">
      <h4 class="text-center text-success">Login Page...</h4>
      <form  class="container" action="login" method="POST">
      {% csrf_token %}
        <div class="mb-3">
           <label for="exampleInputEmail1" class="form-label">Username</label>
           <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" name="password" id="exampleInputPassword">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        
      </form>
        <div>
           
           {%for message in messages%}
           <p class="text-center text-danger">{{message}}</p>
           {%endfor%} 
       
           <center><p>Don't have accounts <a href="register" ><b>Register</b></a></p></center>
           
        </div>
       

      </div>   
    <div class="col-sm-3"></div>  
  </div>
<div>
{% endblock %}

delhi/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock  %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-3 "></div>
      <div class="col-sm-6 bg-light">
        <h3 class="text-center text-success">Registration Page...</h3>
        <form class="container" action="register" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Username</label>
          <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail2" name="email" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password1">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Confirm_password</label>
          <input type="password" class="form-control" id="exampleInputPassword2" name="password2">
        </div>
  
        <button type="submit" id="btn" class="btn btn-primary">Register</button>
        </form>
      <div>
      </div>
           {%for message in messages%}
           <p class="text-center text-success">{{message}}</p>
           {%endfor%} 
          <center><p>If you have already registered <a href="login" ><b>Login</b></a></p></center>
      <div class="col-sm-3"></div>
  </div>
</div>
{% endblock%}  

delhi/templates/searching.html
{% extends 'base.html' %}
{% block title %}Searching{% endblock  %}
{% block content %}
<br>
{% if states %}
<div class="container-fluid">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Result</th>
            </tr>
        </thead>
        <tbody>
            {% for state in states %}
            <tr>
                <td><a href="/category/?{{state.name}}">{{state.name}}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% if category %}
<div class="container-fluid">

    <table class="table">
        <thead>
            <tr>
              
                <th scope="col">Result</th>
            </tr>
        </thead>
        <tbody>
            {% for cat in category %}
            <tr>
               
                <td><a href="/subcategory/?{{cat.name}}"> {{cat.name}}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% if subcategory %}
<div class="container-fluid">

    <table class="table">
        <thead>
            <tr>
                <th scope="col">s_no</th>
                <th scope="col">Result</th>
            </tr>
        </thead>
        <tbody>
            
            {% for sub in subcategory %}
            <tr>
                <th scope="row"></th>
                <td><a href="/subcategory/" > {{sub.name}}</a></td>
            </tr>
            {% endfor %}
         
        </tbody>
    </table>
</div>
{% endif %}

{% if jobs %}
<div class="container-fluid">

    <table class="table">
        <thead>
            <tr>
              
                <th scope="col">Name</th>
                <th scope="col">jobPosition</th>
                <th scope="col">Location</th>
            </tr>
        </thead>
        <tbody>
            
            {% for job in jobs %}
            <tr>
               {% comment %} /companydetails/?{{job.companydetails.name}} {% endcomment %}
                <td><a href="//" style="text-decoration: none;"> {{job.companydetails.name}}</a></td>
                <td>{{job.jobPosition}}</td>
              <td>{{job.Location}}</td>
            </tr>
            {% endfor %}
         
        </tbody>
    </table>
</div>
{% endif %}


{%endblock%}

delhi/templates/state.html
{% extends 'base.html' %}
{% block title %}Category{% endblock  %}
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="left-sidebar">
                <h6>Category</h6>
			          <div class="panel-group category-products brands_products">						
                  {%for ct in category%}			
					        <div class="panel panel-default">
						        <div class="panel-heading">
							        <h6 class="panel-title"><a href="/?category={{ct.id}}">{{ct.category}}</a></h6>
						        </div>
				          </div>
                  {%endfor%}						
			          </div>
            </div>
        </div>    
        <div class="col-sm">
           One of three columns
        </div>
        <div class="col-sm">
           One of three columns
        </div>
    </div>
</div>
{% endblock  %}

delhi/templates/subcategory.html
{% extends 'base.html' %}
{% block title %}SubCategory Scraping{% endblock  %}
{% block content %}
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      <table class="table">   
        <tbody>
          <tr>        
            <td><a type="submit" href="/subcategory/?name" style="text-decoration: none; color:brown" name="sub" id="sub">All SubCategory here...</a></td>
          </tr>
            {% for sub in subcategory%}
              <tr>       
                <td><a href="/job/?{{sub.name}}" style="text-decoration: none;">{{sub.name}}</a></td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-sm-9">
    <form class="d-flex" action="/searchingsub" method="get">{% csrf_token %}
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search"  id="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>    
</div>

{% endblock  %}      